name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Drugs Quiz ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: build
        run: pyinstaller app.spec

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/github-script@0.9.0
        id: upload_url
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |

            const result = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: ${{ steps.get_version.outputs.VERSION }},
            });

            console.log(result.data.upload_url)

            return result.data.upload_url



      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_url.outputs.result }}
          asset_path: ./dist.zip
          asset_name: drugs-quiz-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}.zip
          asset_content_type: application/octet-stream
